### ISSUE TITLE
Kinesis Video Stream Support

### ISSUE THREAD

**Issue by harishsune** [awslabs/amazon-kinesis-client-net#16]
Is there any way to inject video stream to Kinesis Video?
Normal streaming request as **PutRecord()** but while using **AmazonKinesisVideoClient** class it does not expose any PutMedia(). 
Java SDK has support for this,but any chances to have it in .Net SDK as well?

**Comment by pfifer** [comment]
This project is for processing data from Kinesis Data Streams.  You might try asking on the [AWS .NET SDK GitHub](https://github.com/aws/aws-sdk-net).
