### ISSUE TITLE
Kinesis - Empty Payload 

### ISSUE THREAD

**Issue by francoisdutoit** [awslabs/amazon-kinesis-client-net#18]
Hi,
I'm currently able to do a GetMedia request - however - I never get any data back.
Below is the code that I am using and attached are some screenshots of my object contents after the call.

I have checked in the AWS console and the video that I am pushing to Kinesis is showing there...
Any ideas why this could be happening?  ( See attached screenshots )

Thanks!

           var dataEndPoint = _videoClient.GetDataEndpoint(getDataEndpointRequest).DataEndpoint;
            var videoMediaClient = new AmazonKinesisVideoMediaClient(dataEndPoint, _credentials);

            var mediaRequest = new GetMediaRequest()
            {
                StreamARN = _streamARN,
                StartSelector = new StartSelector
                {
                    StartSelectorType = StartSelectorType.EARLIEST
                },
            };

            GetMediaResponse getMediaResponse = new GetMediaResponse();
            try
            {
                getMediaResponse = videoMediaClient.GetMedia(mediaRequest);

            }
            catch(Exception ex)

![1](https://user-images.githubusercontent.com/9386768/37026818-39c2e526-2138-11e8-993b-f260c9a4fc24.JPG)
![2](https://user-images.githubusercontent.com/9386768/37026819-39f1adc0-2138-11e8-828b-bc8019bc429b.JPG)

**Comment by pfifer** [comment]
This repository is for consuming from Amazon Kinesis Streams, and not consuming from Amazon Kinesis Video Streams.  I think it might be better to post your question on the [AWS SDK for .NET](https://github.com/aws/aws-sdk-net) or on the [AWS Forums for Amazon Kinesis Video Streams](https://forums.aws.amazon.com/forum.jspa?forumID=282)
