### ISSUE TITLE
How to assume role while using KCL-Net 

### ISSUE THREAD

**Issue by vaibhavbilgikar** [awslabs/amazon-kinesis-client-net#22]
I am trying to use STSAssumeRoleSessionCredentialsProvider with following entry in the KCL.Properties file.

AWSCredentialsProvider = STSAssumeRoleSessionCredentialsProvider|arn:aws:iam::<account id>:role/<role name>|<session name>.

However the Bootstrap is giving following error :  

Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.prepare(MultiLangDaemonConfig.java:116)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:107)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:77)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:64)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:134)

Please let me know if  you need additional information

**Comment by pfifer** [comment]
There is a way but requires adding the dependency required for STS credentials.  [See this approach for Python](https://github.com/awslabs/amazon-kinesis-client-python/issues/51#issuecomment-316467366).  It does work effectively the same, the maven plugin will generate a startup script for both shell, and cmd batch.

**Comment by vaibhavbilgikar** [comment]
Thank you Pfifer.
Let me get the log information to understand the problem, as mentioned in your link.

**Comment by pfifer** [comment]
If all goes well you shouldn't need the logging.  That version of the pom.xml just includes logback, and you can configure it as described.  The pom.xml also includes the STS provider dependency so it should just work.  I would recommend doing two things:
1. Updating the `aws-java-sdk.version` to the most recent version, which looks to be 1.11.381.
2. Updating the version for `amazon-kinesis-client` to 1.9.0

Setting environment variable for a batch script are slightly different than for shell scripts. So setting  the `CLASSPATH_PREFIX=./logback` variable may take some testing.

**Comment by vaibhavbilgikar** [comment]
Hi Pfifer,

I am sorry but I am kind of stuck after getting the script in "target/appassembler/bin/multilang-daemon" folder by running the command "Apache Maven " on the latest pom.xml file you have shared in the forum. ( I changed the aws-java-sdk.version to 1.11.381 and amazon-kinesis-client to 1.9.0 in the pom.xml before running the commnand : "Apache Maven " )

Then I ran the script as 
  multilang-daemon.bat ..\kcl.properties

This gave so many errors on the console screen that I can not even past it here.

To give my background, I am a Net developer (not much experience in JAVA). Thats the reason I am using 
"amazon-kinesis-client-net" and included following Maven packages in C# code in Bootstrap project.

It will be nice if you can guide me with the changes to be done in existing BootStrap project which is in ".Net Core 2.0" to get rid of the exception occurring when I add AWSCredentialsProvider = STSAssumeRoleSessionCredentialsProvider|arn:aws:iam:::role/|. in KCL.properties file

Maven Packages included in C# code are : 
 private static readonly List<MavenPackage> MAVEN_PACKAGES = new List<MavenPackage>()
        {
            new MavenPackage("com.amazonaws", "amazon-kinesis-client", "1.9.0"),
            new MavenPackage("com.amazonaws", "aws-java-sdk-dynamodb", "1.11.273"),
            new MavenPackage("com.amazonaws", "aws-java-sdk-s3", "1.11.273"),
            new MavenPackage("com.amazonaws", "aws-java-sdk-kms", "1.11.273"),
            new MavenPackage("com.amazonaws", "aws-java-sdk-core", "1.11.273"),
            new MavenPackage("org.apache.httpcomponents", "httpclient", "4.5.2"),
            new MavenPackage("org.apache.httpcomponents", "httpcore", "4.4.4"),
            new MavenPackage("commons-codec", "commons-codec", "1.9"),
            new MavenPackage("com.fasterxml.jackson.core", "jackson-databind", "2.6.6"),
            new MavenPackage("com.fasterxml.jackson.core", "jackson-annotations", "2.6.0"),
            new MavenPackage("com.fasterxml.jackson.core", "jackson-core", "2.6.6"),
            new MavenPackage("com.fasterxml.jackson.dataformat", "jackson-dataformat-cbor", "2.6.6"),
            new MavenPackage("joda-time", "joda-time", "2.8.1"),
            new MavenPackage("com.amazonaws", "aws-java-sdk-kinesis", "1.11.273"),
            new MavenPackage("com.amazonaws", "aws-java-sdk-cloudwatch", "1.11.273"),
            new MavenPackage("com.google.guava", "guava", "18.0"),
            new MavenPackage("com.google.protobuf", "protobuf-java", "2.6.1"),
            new MavenPackage("commons-lang", "commons-lang", "2.6"),
            new MavenPackage("commons-logging", "commons-logging", "1.1.3"),
            new MavenPackage("com.amazonaws", "aws-java-sdk", "1.11.381")
        };

**Comment by pfifer** [comment]
If you don't mind modifying the Bootstrap project just add
``` c#
new MavenPackage("com.amazonaws", "aws-java-sdk-sts", "1.11.273")
```
You do want the version of the AWS Java SDK to match for all the components.

**Comment by vaibhavbilgikar** [comment]
Or may be we can take it in this way,

If I am using amazon-kinesis-client-net, then what all changes I would need to do in the latest source code available on GitHub. 
I have the Kinesis stream arn and the role arn with me. Both of them belongs to different AWS account I also have an IAM user which can assume that particular role.

**Comment by vaibhavbilgikar** [comment]
Even after adding 
new MavenPackage("com.amazonaws", "aws-java-sdk-sts", "1.11.273" (Which I did earlier)
I am still getting following error :  
INFO: Using workerId: 712aa121-bcd5-4494-8399-d2dd50a927ae
Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
        at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.prepare(MultiLangDaemonConfig.java:116)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:107)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:77)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.<init>(MultiLangDaemonConfig.java:64)
        at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:134)
======================
Exiting Bootstrap...


I am keeping access key id and secrete access key in the file "credentials" in ".AWS" folder in my local user profile.

**Comment by vaibhavbilgikar** [comment]
Even after adding
new MavenPackage("com.amazonaws", "aws-java-sdk-sts", "1.11.273" (Which I did earlier)
I am still getting following error :
INFO: Using workerId: 712aa121-bcd5-4494-8399-d2dd50a927ae
Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.prepare(MultiLangDaemonConfig.java:116)
at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.(MultiLangDaemonConfig.java:107)
at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.(MultiLangDaemonConfig.java:77)
at com.amazonaws.services.kinesis.multilang.MultiLangDaemonConfig.(MultiLangDaemonConfig.java:64)
at com.amazonaws.services.kinesis.multilang.MultiLangDaemon.main(MultiLangDaemon.java:134)
Exiting Bootstrap...

I am keeping access key id and secrete access key in the file "credentials" in ".AWS" folder in my local user profile.

**Comment by pfifer** [comment]
In this case the logging configuration described above is important.  It's possible that the loading of the default credentials are failing, and debug logging would indicate that.

**Comment by vaibhavbilgikar** [comment]
Right !  Let me gather the debug logs which will help us get some pointers.

**Comment by vaibhavbilgikar** [comment]
Sorry to bother you again
Is there any way to get the logs without using the POM.xml file.
Can I do some changes in BootStrap launchSettings.json file or KCL.properties file ?

**Comment by pfifer** [comment]
Unfortunately it's not easy as it requires that a logging system is available.  What are the errors you're getting when running the batch script?

Also is this with Windows or another OS?

**Comment by vaibhavbilgikar** [comment]
Let me get the errors in a text file when I run the batch script.
I am using Windows Server 2016 with Visual Studio 2017 community edition.

**Comment by vaibhavbilgikar** [comment]
Hello Justine,

Extremely sorry for not continuing the thread. The issue got resolved finally.
The issue was because of the improper IAM role.

To explain it in brief:

We have the Kinesis consumer (using KCL) running in Azure VM and the team been given an AccessKeyId and AccessKeySecrete of an IAM user to be used in consumer app.
Of Course, the role defined in the AWS account in which the kinesis stream is instantiated / hosted is trusting this particular user. 
Now along with access to Kinesis, KCL also requires access to MangoDb and CloudWatch. The IAM user being used by consumer app was not having sufficient privileges to access to any of these AWS services. And that was the problem.

**Comment by vaibhavbilgikar** [comment]
The next challenge is how to get key (symmetric encryption key) stored in AWS Key Management Service. 
After I receive message in the method : ProcessRecords, I need to decrypt the message with help of key stored in KSM.

**Comment by vaibhavbilgikar** [comment]
Thank you Justin.

**Comment by pfifer** [comment]
I'm glad to hear you were able to get everything working.  I'm going to resolve this for now feel free to reopen if you need additional assistance.
