### ISSUE TITLE
Manual shutdown of the consumer

### ISSUE THREAD

**Issue by tomsfernandez** [awslabs/amazon-kinesis-client-net#23]
Hi, can I manually shutdown the consumer with the Shutdown method?

**Comment by pfifer** [comment]
The `shutdown(...)` method is called by the Java code when a lease is lost or shard is ended.  Calling it yourself will not change the state that the Java code believes the consumer is in. 

If you're on a *nix system killing the process with `TERM` (generally this is the default signal) will cause the Java process to gracefully shutdown all consumers, and exit.  I don't know if there is a way to do something similar on Windows.  It appears that Java will trigger shutdown hooks if you use Control-C to terminate the process, other methods may or may not work.  If you're looking into it the way graceful shutdown is implemented is via [`Runtime#addShutdownHook(Thread)`](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-).
