### ISSUE TITLE
Use 2.0 version of KCL?

### ISSUE THREAD

**Issue by deepthakannan** [awslabs/amazon-kinesis-client-net#27]
The [new](https://github.com/awslabs/amazon-kinesis-client/tree/master) KCL seems to have support for [streaming and other great stuff](https://github.com/awslabs/amazon-kinesis-client/blob/master/CHANGELOG.md#release-200-august-02-2018). 

[Bootstrap step](https://github.com/awslabs/amazon-kinesis-client-net/blob/master/Bootstrap/Bootstrap.cs#L137) in this project uses [1.x](https://github.com/awslabs/amazon-kinesis-client/tree/v1.x) version whereas active development happens on 2.0 version of KCL. 

Any thoughts on support for 1.x version going forward, production readiness of KCL 2.0 (especially new code is pushed almost every day), backwards compatibility of multilangdaemon clients, etc for someone starting to write new projects?

**Comment by pfifer** [comment]
Closing this in favor of #30
