### ISSUE TITLE
Project still alive ?

### ISSUE THREAD

**Issue by draudrau** [awslabs/amazon-kinesis-client-net#76]
Hello,

I just want to know if this project still alive ?
There is no change since the last 3 years.
I plan to use this nuget soon. Can I ?

Best regards.

**Comment by brendan-p-lynch** [comment]
Yes this project is still alive. Feel free to engage, write code, and use as you see fit. We primarily do updates to features in the java package and port those changes over: https://github.com/awslabs/amazon-kinesis-client/tree/master
