### ISSUE TITLE
Supporting .NET Core

### ISSUE THREAD

**Issue by aignas** [awslabs/amazon-kinesis-client-net#8]
It would be great if this library supported .NET Core.

As shown on https://icanhasdot.net/result?github=awslabs~2Famazon-kinesis-client-net, this library at the moment has dependencies which do not support .NET Core, however for some the porting is underway:
- **Stateless**: https://github.com/dotnet-state-machine/stateless/pull/75
- **CommandLine**: https://github.com/gsscoder/commandline/tree/dotnet-core

**Comment by shakdoesgithub** [comment]
we also have a need for this.  
Stateless has already pushed a dotnet core compatible package to nuget.
The CommandLine guys are pushing their dotnet core package out next week.

Is there a plan to convert this to dotnet core?

**Comment by pfifer** [comment]
We'll be looking at updating the .NET client, and at the same time investigate the update to .NET Core.  I don't have an ETA at this time.

**Comment by simonpetty** [comment]
Hi.
I'm relatively new to GitHub processes, but I've managed to port this to .NET Core.
Stateless now supports it: https://www.nuget.org/packages/Stateless/3.1.0
CommandLine beta version supports it: https://www.nuget.org/packages/CommandLineParser/2.1.1-beta
WebClient is coming in .NET Core 2, but have replaced this with a simple HttpClient version.

Would a pull request with this be worth submitting?

**Comment by rodrigovidal** [comment]
any news on this one?

**Comment by khaledsobhy83** [comment]
I took my chances and started on supporting .Net Core. The problem mainly is that the latest .Net Core version of Stateless library introduced queuing while firing triggers which means when calling .Fire method does not mean that it will be actually fired but it will be queued when a parent process is still firing so the KCL state-machine configurations and handling should be updated accordingly. I am almost done with it and will request a merge soon, maybe this week.

**Comment by simonpetty** [comment]
I ended up rolling my own, based on this code and the underlying protocol. I think it's probably not wise to put code like this into production as is, due to lack of support - as this issue demonstrates.

**Comment by scottctr** [comment]
You may want to look at [NStateManager](https://github.com/scottctr/NStateManager). It has very similar functionality as Stateless, but does not use a queue. Just post to Issues there if there's anything I can help with.

**Comment by victorkirov** [comment]
Any news or ETA on this?

**Comment by victorkirov** [comment]
There is feedback from ```stateless``` team here:
https://github.com/dotnet-state-machine/stateless/issues/223

Could that work?

**Comment by HenningNT** [comment]
Hi guys, could you check out this (stateless) PR :
https://github.com/dotnet-state-machine/stateless/pull/246

It adds the option of disabling queueing when Fire() is called. I hope that would work for you.

**Comment by khaledsobhy83** [comment]
I have used the Stateless PR recommended by @HenningNT and it is working just fine. I think we are ready for an official .net core of AWS KCL :). I can initiate a PR once Stateless is available on Nuget.

**Comment by vidarw** [comment]
@khaledsobhy83 Do you have a working .NET Core prototype build just waiting for a Stateless to build their package? Trying to determine if I should consume my Kinesis stream via .NET Core, .NET or just fallback to Java.

**Comment by HenningNT** [comment]
I'm getting closer to a new Stateless release. There's a [pre-release ](https://www.nuget.org/packages/Stateless/4.1.0-dev-00307) available now, that most likely will be released as stable.

**Comment by khaledsobhy83** [comment]
@HenningNT Perfect, looking for it

**Comment by HenningNT** [comment]
[Stateless v4.1](https://www.nuget.org/packages/Stateless/4.1.0) is out, I hope it works!

**Comment by poojamalani** [comment]
Hey @khaledsobhy83 now that the stateless fix is officially released, any ETA on a .Net Core version of the KCL? Thanks!

**Comment by khaledsobhy83** [comment]
@poojamalani I am currently on vacation, will be back in a week and will create a BR with the .net core version, then it is up to the reviewers to decide when it can be officially released.

**Comment by poojamalani** [comment]
@khaledsobhy83 sounds good. Even a PreRelease version will be helpful. Thanks!

**Comment by khaledsobhy83** [comment]
I have submitted PR with the .net core version of the library. Hope someone reviews it...I will be dedicated for fixing any comments/issues to release it ASAP. 
@HenningNT thanks a lot for your help to reach this state.

**Comment by pfifer** [comment]
I will look at the PR today.

**Comment by khaledsobhy83** [comment]
I think this should be closed now.

**Comment by sachabarber** [comment]
Guys I wonder if any of you would know what's going on with this issue, seems related to this one 


https://github.com/awslabs/amazon-kinesis-client-net/issues/28
