### ISSUE TITLE
Incorrect json property used in client -> multilang checkpoint call.

### ISSUE THREAD

**Issue by seanpd** [awslabs/amazon-kinesis-client-net#9]
Checkpointing fails on the most recent KCL multilang daemon.
Right now after a checkpoint call occurs, the client will stop listening for multilang messges.

Right now the exceptions aren't clearly logged, see https://github.com/awslabs/amazon-kinesis-client/issues/122

ClientLibrary.cs:430
[DataMember(Name = "checkpoint")]
--should be changed to--
[DataMember(Name = "sequenceNumber")]

**Comment by pfifer** [comment]
This was completed in PR #10.

**Comment by pfifer** [comment]
Feel free to reopen if you have any more questions.

**Comment by seanpd** [comment]
Thanks!!

-s
